# Generated by Django 3.1.7 on 2021-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210221_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
