# Generated by Django 3.1.7 on 2021-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('CLOSED', 'Close')], default='ACTIVE', max_length=10),
        ),
    ]
